{
    "name": "Tích hợp QLKH - QLCV IT",
    "summary": "Quản lý khách hàng, công việc và AI nội bộ cho quy trình tư vấn giải pháp CNTT",
    "version": "15.0.1.0.0",
    "category": "Sales/CRM",
    "author": "Nhóm sinh viên FIT-DNU",
    "license": "LGPL-3",
    "depends": ["crm", "project", "mail", "calendar", "nhan_su"],
    "data": [
        "security/it_solution_crm_security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/ir_cron_data.xml",
        "views/root_menu_views.xml",
        "views/res_config_settings_views.xml",
        "views/ai_assistant_views.xml",
        "views/ai_chat_views.xml",
        "views/consultation_session_views.xml",
        "views/crm_lead_views.xml",
        "views/project_project_views.xml",
        "views/project_task_views.xml",
        "views/operation_log_views.xml",
        "views/report_views.xml",
        "views/menu_views.xml",
        "views/app_visibility.xml",
    ],
    "demo": [
        "demo/demo_data.xml",
    ],
    "application": False,
    "installable": True,
}
