services:
  db:
    image: postgres:10-alpine
    container_name: it_solution_crm_local_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /data/postgres
    volumes:
      - it_solution_pgdata:/data/postgres
    ports:
      - "5431:5432"

  odoo:
    image: odoo:15
    container_name: it_solution_crm_local_odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./custom_addons:/mnt/extra-addons
      - ./addons:/mnt/odoo-addons
    command:
      - odoo
      - --db_host=db
      - --db_user=odoo
      - --db_password=odoo
      - --addons-path=/mnt/extra-addons,/mnt/odoo-addons,/usr/lib/python3/dist-packages/odoo/addons
      - -d
      - it_solution_crm_demo
      - -i
      - nhan_su,it_solution_crm
      - -u
      - nhan_su,it_solution_crm

volumes:
  it_solution_pgdata:

